
message(STATUS "cpack config")

set(CPACK_PACKAGE_NAME "libqtimwidgets")
set(CPACK_PACKAGE_VERSION ${${PROJECT_NAME}_VERSION})
set(CPACK_PACKAGE_VERSION_MAJOR ${${PROJECT_NAME}_MAJOR_VERSION})
set(CPACK_PACKAGE_VERSION_MINOR ${${PROJECT_NAME}_MINOR_VERSION})
set(CPACK_PACKAGE_VERSION_PATCH ${${PROJECT_NAME}_PATCH_VERSION})

set(CPACK_PACKAGE_VENDOR "АО НИИ «Вектор»")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Set of additional QWidget c++")
set(CPACK_PACKAGE_CONTACT "Udychak Timur <Udychak_TA@vector.ru>")

set(CPACK_GENERATOR DEB)

# debian
set(CPACK_DEBIAN_PACKAGE_RELEASE 1)
set(CPACK_DEBIAN_PACKAGE_SECTION "devel")
set(CPACK_DEB_COMPONENT_INSTALL ON)
if(NOT CMAKE_LESS_V3)
    set(CPACK_DEBIAN_ENABLE_COMPONENT_DEPENDS ON)
    set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
    set(CPACK_DEBIAN_PACKAGE_GENERATE_SHLIBS ON)
    set(CPACK_DEBIAN_PACKAGE_GENERATE_SHLIBS_POLICY ">=")
endif(NOT CMAKE_LESS_V3)

set(CPACK_DEBIAN_SHLIB_PACKAGE_NAME ${CPACK_PACKAGE_NAME})
set(CPACK_DEBIAN_SHLIB_FILE_NAME DEB-DEFAULT)

set(CPACK_DEBIAN_DEV_PACKAGE_NAME ${CPACK_PACKAGE_NAME}-dev)
set(CPACK_DEBIAN_DEV_FILE_NAME DEB-DEFAULT)
set(CPACK_COMPONENT_DEV_DESCRIPTION
    "Developement files for qtimwidgets")
