include(TUtils)
include(CMakePackageConfigHelpers) 
macro(t_configure_targets_export)
    set(options CONFIGURE_LIB CONFIGURE_EXE CREATE_VERSION CREATE_CONFIG)
    set(oneValueArgs PACKAGE_NAME PACKAGE_NAME COMPONENT COMPATIBILITY INSTALL_PREFIX INSTALL_DESTINATION INSTALL_INCLUDES ROOT_TARGET BUILD_TREE_EXPORT_PATH)
    set(multiValueArgs TARGETS_NAMES)

    cmake_parse_arguments(_PCN "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    t_check_param(_PCN_PACKAGE_NAME "PACKAGE_NAME" "t_configure_targets_export")
    t_check_param(_PCN_INSTALL_PREFIX "INSTALL_PREFIX" "t_configure_targets_export")
    t_check_param(_PCN_BUILD_TREE_EXPORT_PATH "BUILD_TREE_EXPORT_PATH" "t_configure_targets_export")

    set(_PCN_CONFIG_LIBRARY_FILE_IN ${CMAKE_SOURCE_DIR}/cmake/Config.cmake.in)

    if(NOT DEFINED _PCN_INSTALL_DESTINATION)
        set(_PCN_INSTALL_DESTINATION ${_PCN_PACKAGE_NAME})
    endif(NOT DEFINED _PCN_INSTALL_DESTINATION)
    set(_PCN_EXPORT_INSTALL_DESTINATION
        "${CMAKE_INSTALL_LIBDIR}/cmake/${_PCN_INSTALL_DESTINATION}")

    if(NOT DEFINED _PCN_INSTALL_INCLUDES)
        set(_PCN_INSTALL_INSTALL_INCLUDES ${CMAKE_INSTALL_INCLUDEDIR})
    endif(NOT DEFINED _PCN_INSTALL_INCLUDES)

    if(NOT DEFINED _PCN_COMPONENT)
        set(_PCN_COMPONENT "dev")
    endif(NOT DEFINED _PCN_COMPONENT)

    if(NOT DEFINED _PCN_ROOT_TARGET)
        foreach(export_tgt ${_PCN_TARGETS_NAMES})
            if(DEFINED _PCN_CONFIG_NOT_TARGETS)
                set(_PCN_CONFIG_NOT_TARGETS "${_PCN_CONFIG_NOT_TARGETS} AND ")
            endif(DEFINED _PCN_CONFIG_NOT_TARGETS)
            set(_PCN_CONFIG_NOT_TARGETS "${_PCN_CONFIG_NOT_TARGETS}NOT TARGET ${export_tgt}")
        endforeach(export_tgt)
    else(NOT DEFINED _PCN_ROOT_TARGET)
        set(_PCN_CONFIG_NOT_TARGETS "NOT TARGET ${_PCN_ROOT_TARGET}")
    endif(NOT DEFINED _PCN_ROOT_TARGET)

    if(NOT DEFINED _PCN_COMPATIBILITY)
        set(_PCN_COMPATIBILITY SameMajorVersion)
    endif(NOT DEFINED _PCN_COMPATIBILITY)

    set(_PCN_OUTPUT_CONFIG_LIBRARY "${_PCN_PACKAGE_NAME}Config.cmake")
    set(_PCN_OUTPUT_CONFIG_VERSION "${_PCN_PACKAGE_NAME}ConfigVersion.cmake")
    set(PROJECT_VERSION ${${PROJECT_NAME}_VERSION})
    t_debug("PACKAGE_NAME = ${_PCN_PACKAGE_NAME}")
    t_debug("TARGETS_NAMES = ${_PCN_TARGETS_NAMES}")
    t_debug("NO_BUILD_TREE_EXPORT = ${_PCN_NO_BUILD_TREE_EXPORT}")
    t_debug("CONFIG_NOT_TARGETS = ${_PCN_CONFIG_NOT_TARGETS}")
    t_debug("CMAKE_FILES_DIRECTORY = ${CMAKE_FILES_DIRECTORY}")
    t_debug("_PCN_BUILD_TREE_EXPORT_PATH = ${_PCN_BUILD_TREE_EXPORT_PATH}")
    t_debug("PROJECT_VERSION = ${PROJECT_VERSION}")
    t_debug("_PCN_OUTPUT_CONFIG_VERSION = ${_PCN_OUTPUT_CONFIG_VERSION}")
    t_debug("_PCN_INSTALL_INCLUDES = ${_PCN_INSTALL_INCLUDES}")
    t_debug("_PCN_EXPORT_INSTALL_DESTINATION = ${_PCN_EXPORT_INSTALL_DESTINATION}")
    t_debug("_PCN_COMPONENT = ${_PCN_COMPONENT}")


    if(NOT DEFINED ${_PCN_PACKAGE_NAME}_TARGET_EXPORT_FILE)
        set(${_PCN_PACKAGE_NAME}_TARGET_EXPORT_FILE
            "${_PCN_BUILD_TREE_EXPORT_PATH}/${_PCN_PACKAGE_NAME}Targets.cmake")
        export(TARGETS ${_PCN_TARGETS_NAMES}
            FILE ${${_PCN_PACKAGE_NAME}_TARGET_EXPORT_FILE})
    else(NOT DEFINED ${_PCN_PACKAGE_NAME}_TARGET_EXPORT_FILE)
        export(TARGETS ${_PCN_TARGETS_NAMES}
            FILE APPEND ${${_PCN_PACKAGE_NAME}_TARGET_EXPORT_FILE})
    endif(NOT DEFINED ${_PCN_PACKAGE_NAME}_TARGET_EXPORT_FILE)
    t_debug("${_PCN_PACKAGE_NAME}_TARGET_EXPORT_FILE = ${${_PCN_PACKAGE_NAME}_TARGET_EXPORT_FILE}")
    if(_PCN_CREATE_VERSION)
        write_basic_package_version_file(
            ${_PCN_BUILD_TREE_EXPORT_PATH}/${_PCN_OUTPUT_CONFIG_VERSION}
            VERSION ${PROJECT_VERSION}
            COMPATIBILITY ${_PCN_COMPATIBILITY})
    endif(_PCN_CREATE_VERSION)

    set(PACKAGE_INIT "@PACKAGE_INIT@")
    set(PACKAGE_INCLUDE_INSTALL_DIR "@PACKAGE_INCLUDE_INSTALL_DIR@")
    set(PACKAGE_SYSCONFIG_INSTALL_DIR "@PACKAGE_SYSCONFIG_INSTALL_DIR@")

    if(_PCN_CREATE_CONFIG)
        if(_PCN_CONFIGURE_LIB)
            set(INCLUDE_INSTALL_DIR ${_PCN_INSTALL_INCLUDES})
            configure_file(${_PCN_CONFIG_LIBRARY_FILE_IN}
                "${_PCN_BUILD_TREE_EXPORT_PATH}/${CMAKE_FILES_DIRECTORY}/${_PCN_OUTPUT_CONFIG_LIBRARY}.in" @ONLY)
            if(CMAKE_LESS_V31)
                configure_package_config_file(${_PCN_BUILD_TREE_EXPORT_PATH}/${CMAKE_FILES_DIRECTORY}/${_PCN_OUTPUT_CONFIG_LIBRARY}.in
                    ${_PCN_BUILD_TREE_EXPORT_PATH}/${CMAKE_FILES_DIRECTORY}/${_PCN_OUTPUT_CONFIG_LIBRARY}
                    INSTALL_DESTINATION ${_PCN_INSTALL_PREFIX}/${_PCN_EXPORT_INSTALL_DESTINATION}
                    PATH_VARS INCLUDE_INSTALL_DIR)
            else(CMAKE_LESS_V31)
                configure_package_config_file(${_PCN_BUILD_TREE_EXPORT_PATH}/${CMAKE_FILES_DIRECTORY}/${_PCN_OUTPUT_CONFIG_LIBRARY}.in
                    ${_PCN_BUILD_TREE_EXPORT_PATH}/${CMAKE_FILES_DIRECTORY}/${_PCN_OUTPUT_CONFIG_LIBRARY}
                    INSTALL_PREFIX ${_PCN_INSTALL_PREFIX}
                    INSTALL_DESTINATION ${_PCN_EXPORT_INSTALL_DESTINATION}
                    PATH_VARS INCLUDE_INSTALL_DIR)
            endif(CMAKE_LESS_V31)
        endif(_PCN_CONFIGURE_LIB)
    endif(_PCN_CREATE_CONFIG)

    install(FILES
        "${_PCN_BUILD_TREE_EXPORT_PATH}/${CMAKE_FILES_DIRECTORY}/${_PCN_OUTPUT_CONFIG_LIBRARY}"
        "${_PCN_BUILD_TREE_EXPORT_PATH}/${_PCN_OUTPUT_CONFIG_VERSION}"
        DESTINATION "${_PCN_EXPORT_INSTALL_DESTINATION}"
        COMPONENT ${_PCN_COMPONENT})

    install(EXPORT ${_PCN_PACKAGE_NAME}Targets
        DESTINATION "${_PCN_EXPORT_INSTALL_DESTINATION}"
        COMPONENT ${_PCN_COMPONENT})
    t_debug("EXPORT = ${_PCN_PACKAGE_NAME}Targets")
    t_debug("DESTINATION = ${_PCN_EXPORT_INSTALL_DESTINATION}")
    if(NOT _PCN_NO_BUILD_TREE_EXPORT)

        if(_PCN_CREATE_CONFIG)
            if(_PCN_CONFIGURE_LIB)
                set(INCLUDE_INSTALL_DIR ${PROJECT_SOURCE_DIR})
                configure_file(${_PCN_CONFIG_LIBRARY_FILE_IN}
                    "${_PCN_BUILD_TREE_EXPORT_PATH}/${_PCN_OUTPUT_CONFIG_LIBRARY}.in" @ONLY)
                if(CMAKE_LESS_V31)
                    configure_package_config_file(${_PCN_BUILD_TREE_EXPORT_PATH}/${_PCN_OUTPUT_CONFIG_LIBRARY}.in
                        ${_PCN_BUILD_TREE_EXPORT_PATH}/${_PCN_OUTPUT_CONFIG_LIBRARY}
                        INSTALL_DESTINATION ${CMAKE_CURRENT_BINARY_DIR}/${CMAKE_CURRENT_BINARY_DIR}
                        PATH_VARS INCLUDE_INSTALL_DIR)
                else(CMAKE_LESS_V31)
                    configure_package_config_file(${_PCN_BUILD_TREE_EXPORT_PATH}/${_PCN_OUTPUT_CONFIG_LIBRARY}.in
                        ${_PCN_BUILD_TREE_EXPORT_PATH}/${_PCN_OUTPUT_CONFIG_LIBRARY}
                        INSTALL_PREFIX ${CMAKE_CURRENT_BINARY_DIR}
                        INSTALL_DESTINATION ${CMAKE_CURRENT_BINARY_DIR}
                        PATH_VARS INCLUDE_INSTALL_DIR)
                endif(CMAKE_LESS_V31)
            endif(_PCN_CONFIGURE_LIB)
        endif(_PCN_CREATE_CONFIG)

    endif(NOT _PCN_NO_BUILD_TREE_EXPORT)
endmacro(t_configure_targets_export)
